### ISSUE TITLE
 What is a Neural Network?

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide-articles#117]
#### Suggested Reading:

http://karpathy.github.io/neuralnets/

**Comment by tjgerot** [comment]
[Here](http://pastebin.com/aBYVhG23) is a rough draft, let me know your thoughts!

**Comment by atjonathan** [comment]
@tjgerot, looks good! Would you be interested in creating a video with this script?
Tagging @QuincyLarson, @brianamarie and @SEGrooms for a review!

**Comment by QuincyLarson** [comment]
@tjgerot Thanks! This is good information, and it's well written. 

This said, these concepts should spread across several videos (this script alone is 800 words, and normal human speaking rate is only about 150 words per minute.)

Also, I would not recommend reading a script verbatim but rather having talking points. So your talking points may be something like:

- Machine learning is a field of artificial intelligence.
- it aims to give computers the same decision making skills humans use 
- For example...
-We can train computers to learn from data using neural networks, which are similar to how the human brain processes information and makes a decision.

I wouldn't include any more than that in a single video. These videos should be as short (2 minutes at absolute longest) and as modular as possible, and you can have many of them. For example, you might do a video just showing layers and weights. We should keep jargon to a minimum, even if it was introduced in a previous video.

**Comment by atjonathan** [comment]
:+1:

**Comment by SEGrooms** [comment]
This is going to be awesome!

**Comment by tjgerot** [comment]
@atjonathan Sure! What style would you like the video? 3D animations, diagrams, Khan Academy-esque drawing, in person whiteboard, or combinations?

@QuincyLarson Glad to hear this should be split up. I can easily make this with little to no jargon, however I'm not sure how in depth you think the videos should go. Although the majority of the neural network structure only uses basic matrix multiplication (high school algebra), to go into back-propagation would require a high school level calculus background in derivatives, [demonstrated here](https://www.cs.swarthmore.edu/~meeden/cs81/s10/BackPropDeriv.pdf).

**Comment by QuincyLarson** [comment]
@tjgerot preferably you in person whiteboard. Almost all of our videos so far have followed this time-tested formula. Unless you need to specifically show the computer screen (like @brianamarie does in her Chrome DevTools videos) the entire video can be you in front of a whiteboard. The lower-tech looking, the better (as long as the audio and video are reasonably good). 

Here are @brianamarie's tips for recording these: https://github.com/FreeCodeCamp/hikes

Note that we're serious when we say the videos should be less than 2 minutes. If a video seems like it will take longer than that, I recommend breaking its contents down into component parts.

**Comment by SEGrooms** [comment]
@tjgerot have you considered writing a Medium post for FCC? I think this will help you in delivering a 2 minute video. It can be challenging partitioning your material into 2 minute chunks, but since neural nets are such a hot topic, both Medium and Videos would be beneficial for campers.
