### ISSUE TITLE
How to optimize a page for loadtime

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide-articles#127]
We could discuss ways of getting around these considerations: https://developers.google.com/speed/pagespeed/insights/

Perhaps one hike per thing that Google ranks for?

**Comment by ThekhoN** [comment]
Workflow - Optimizing Images - opinionated:

**Images account for 64% of the average page’s payload**
http://www.webperformancetoday.com/2015/01/14/mobile-page-growth/

.

<h3>Saving/using the right image formats:</h3>
**jpeg** ~ rich photographs/ multi multi-color etc - 55% to 65% quality in PROGRESSIVE
**gif/png** for flat images - flat-colors/infographic style/icons etc

if using **transparent images** ~ save in png24 mode and optimize in tinypng.com

.

<h3>Serving Appropriate Images for different viewports:</h3>
<h4>JS-based methods:</h4>
**Picturefill**:https://scottjehl.github.io/picturefill/
example:http://codepen.io/ngaosathe/pen/XXNpEe

**Lazyloading** images/content:
Creates "perception" of faster page load and only loads content in the visible viewport
example:http://codepen.io/ngaosathe/pen/wMgBNe

you can also lazyload background images:
example:http://codepen.io/ngaosathe/pen/zroNNz

[Read Lazyload with lazyloadxt](http://www.smashingmagazine.com/2015/02/redefining-lazy-loading-with-lazy-load-xt/)


<h4>CSS Approach:</h4>
Using good old **background url** to serve appropriate images - via **paddingTop hack** to perfectly fit images.

**Loading appropriate bg image via mediaqueries**
http://codepen.io/ngaosathe/pen/XXpJoo

[Read Which Images Loaded - serving appropriate images](https://timkadlec.com/2012/04/media-query-asset-downloading-results/)
[Read Padding Top Hack](http://alistapart.com/article/creating-intrinsic-ratios-for-video)
[Read more Padding Top Hack](http://tympanus.net/codrops/2014/08/19/making-svgs-responsive-with-css/)

**Comment by brianamarie** [comment]
I think this would be a great series. @ThekhoN your contributions look great - would you be interested in writing more detailed scripts or even recording videos for these hikes? If not, I'm going to mark this as 'help wanted'.

**Comment by ThekhoN** [comment]
I might not be able to record videos but if i can contribute in any way, let me know. Thanks.

**Comment by brianamarie** [comment]
## Help wanted
- [ ] Open an PR with this title into the [video-challenge-tracking](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md) document 
- [ ] Link back to this issue as the title

**Comment by atjonathan** [comment]
@ThekhoN, let us know if you've started scripting yet :smile:

**Comment by ThekhoN** [comment]
Hi just updated the responsive image load via pictureFill.
http://codepen.io/ngaosathe/pen/XXNpEe?editors=0011

```
//load pictureFill ONLY if picture tag NOT supported
var pictureTag_supported = !!window.HTMLPictureElement;
checkPicturefill_req();
function checkPicturefill_req() {
    if (!pictureTag_supported) {
        ['https://cdnjs.cloudflare.com/ajax/libs/picturefill/3.0.1/picturefill.min.js'].forEach(function(src) {
            var script = document.createElement('script');
            script.src = src;
            script.async = true;
            document.head.appendChild(script);
        });
    } else {
        console.log('picture tag supported, picturefill not required!');
    }
}
```
This will ensure that pictureFill is only loaded if the picture tag is not supported by the browser.

Let me know what else you'll need. I think it would be easier to learn and implement these things practically if we could give functional examples instead of just code snippets.

Good day!

**Comment by brianamarie** [comment]
> I think it would be easier to learn and implement these things practically if we could give functional examples instead of just code snippets.

@ThekhoN I think you're right. Maybe the best way to teach these concepts would be a mix of short videos, some tutorials, or even some more traditional coding challenges. What do you think?

**Comment by ThekhoN** [comment]
Sure..let's do that. Sorry, I got a little busy preparing for my first fight.
