### ISSUE TITLE
What does 'Open Source' mean?

### ISSUE THREAD

**Issue by brianamarie** [freeCodeCamp/guide-articles#132]

**Comment by Pandarati** [comment]
"Open Source" is a bit tricky to explain. The average person thinks of free when they hear open source. However, that's not exactly the case. The leader(s) of an Open Source project can create limitations and permissions for it.

Basically in the simplest definition. Open Souce allows "the people" to view it, see it, and suggest improvements for a particular product.

**Comment by carl-parrish** [comment]
Open Source means that the code is available to be reviewed, it can be forked, and they take contributions of code from outside the orgination.

**Comment by brianamarie** [comment]
@Pandarati & @carl-parrish, would either of you be interested in writing scripts or recording videos for this topic?

**Comment by liberaltech** [comment]
Open Source === mindful, transparent, collaborative, peer reviewed.

**Comment by marfarma** [comment]
I'll work on a script for this.  If voice & slides is an acceptable video format, I can probably do that too.

**Comment by atjonathan** [comment]
@marfarma, awesome :tada:, let me or @brianamarie know if you need any help :+1:

**Comment by marfarma** [comment]
How much detail should I include:
  
- Cover the OSI ten points individually, list them or just mention that they exist?  
- Describe the difference between restrictive (copyleft) vs permissive licenses - or just mention that some licenses have distribution restrictions?  
- Explain why 'Public Domain' is not the same as a permissive OS license, or just mention it?

Are there issues that cover these related topics: 

- How do I make my software Open Source?
- How do I comply with Open Source license terms when distributing my application?

I think the first one could be included in this topic, but might be better served as it's own topic, while the second deserves separate coverage -- and might not fit into the mandate for hikes.

**Comment by brianamarie** [comment]
@marfarma 👋 I'm so glad to see this!!! In general, from the sounds of it you have a good grasp of what will fit into a video challenge as well as what's important about Open Source. Thank you for your work here!

> Cover the OSI ten points individually, list them or just mention that they exist?

I defer to your best judgement here - I definitely think it'd be good to note they exist, but how much detail you go into is up to you.

> Describe the difference between restrictive (copyleft) vs permissive licenses - or just mention that some licenses have distribution restrictions?

I think you're on point with noting that some have distribution restrictions. Too much detail might be forgotten after the fact, but the main points of "not all OS licenses are the same in these ways" are important to hit home.  

> Explain why 'Public Domain' is not the same as a permissive OS license, or just mention it?

👍 I think this is a key concept that is worth spending some time on. 

> How do I make my software Open Source?

I definitely think this is worth including! 😄 The level of detail is up to you, but mentioning it will be fantastic ✨ ! 

> How do I comply with Open Source license terms when distributing my application?

I think you're exactly right about this being best served as its own topic. I could see it fitting well into a blog post, but it also may make a great video. Like I said, I think you have plenty of expertise on these and I trust your judgement. 

@marfarma I hope these answers are helpful in any way. Please let me know if there's anything else I can do to help you in any way. 😄 Thank you again for doing this!

**Comment by atjonathan** [comment]
@marfarma, any update on this?

**Comment by brianamarie** [comment]
# Open Source Software

### What is Open Source?
- Software with a certain license and public code base
- Community contributions are welcomed
- Certain rules apply, like those who use the software can't profit from it
- Community driven
- Growing in popularity, even for large enterprise companies

### What is Closed Source?
- Code bases that are proprietary and private

### Why does it matter? 
- Anybody can contribute
- Grow your community and skills
- Employers will look for this
- Skills of working in open source community valuable as well as coding skills
