### ISSUE TITLE
UX: An Overview Of What Makes Up User Experience

### ISSUE THREAD

**Issue by erikasf** [freeCodeCamp/guide-articles#153]
Hi,
I"m not sure if I'm doing this correctly, but I have a feeling you will let me know the error of my ways. Here is a script for a high level overview of User Experience , which would be followed up by deep diving into what each of the different areas do with examples of deliverables from each stage in future videos. 

[User Experience Overview Script](https://docs.google.com/spreadsheets/d/1LbTjDrnEc5tXJkqlQP5xKBvXHGcaSFjHbcMLxQ72ZEo/edit?usp=sharing)

**Comment by brianamarie** [comment]
This looks SO awesome @erikasf! 

My one and only concern is the length of this video. Try to keep videos between 1-3 minutes. For this, that might mean changing nothing, splitting it up, or cutting a little out. I'll leave that up to you. Additionally, please include 1-3 true/false questions with each video later in production so we can include that as part of the hikes to make sure people aren't zoning out. It'll be swipe left/right just like you talk about in the script! 

I'm really excited to see this video and other scripts/videos you create - I know I'll learn a lot, and so will SO many other users. 

If you have any questions for me or anyone else about what you should do next, don't hesitate to ask. I think you should move forward with this. :)

**Comment by erikasf** [comment]
Thanks Briana, and here i was worried that it was going to be to short. I'll get two or three questions together. How would you like those submitted? I'll get the filming of this done tonight or else tomorrow morning. 
thanks for the positive feedback
Erika

**Comment by brianamarie** [comment]
You can just add them at the bottom of the script. Some examples from the
CDN video:

Content Delivery Networks are a service you can buy through your internet
service provider to increase your network connectivity. (F, CDNs are not
provided through ISPs, but are clients of websites that in turn use servers
from an ISP to better deliver the content of the original website to the
user).

CDNs are popular and wide-reaching, and you've probably used one as a
website user many times without even knowing it. The end result is that
your experience was faster than it could have been without the CDNs
services. (T)


Let me know if you need anything else. Just like the math videos that are
being worked on, I'm so excited to see these!

On Tue, Jan 5, 2016 at 5:46 PM, erika <notifications@github.com> wrote:

> Thanks Briana, and here i was worried that it was going to be to short.
> I'll get two or three questions together. How would you like those
> submitted? I'll get the filming of this done tonight or else tomorrow
> morning.
> thanks for the positive feedback
> Erika
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/hikes/issues/153#issuecomment-169171198>.
>



-- 

Briana Swift

Director | Primo Allegro, Allegro Choirs of Kansas City

Private Beginning Piano & Voice Teacher

913-907-4787 | 372bmswift27@gmail.com

**Comment by brianamarie** [comment]
@erikasf Are you still able to help move forward with these videos? I would love to work with you more on these.

For now, I am adding the `help-wanted` tag so other users can make progress on what you've started. 😄

**Comment by CreativeJuggernaut** [comment]
Since this does not look like it is in progress I would like to take over this video and shoot it this weekend. Let me know if there is any issue with that.

**Comment by atjonathan** [comment]
@CreativeJuggernaut, go ahead!

**Comment by erikasf** [comment]
Sorry I became really ill and then I started a medical device company and have been doing the funding rounds. If there is still a need in back and have lots of ideas

**Comment by CreativeJuggernaut** [comment]
No worries Erika. If you want to help do videos. I finally got to start these. I sorted out the technical aspect last week of getting a green screen and things the quality that I was hoping for and am now moving forward. I was ill too a bit last year so that is why this was dillayed

Do you want to hop on a call and talk through these videos next week? I would love to get your ideas integrated and if you want to do any of them lmk.

Chloe 

415-810-6168
Chloebregman@gmail.com
