### ISSUE TITLE
What is TCO (Tail Call Optimization)

### ISSUE THREAD

**Issue by bugron** [freeCodeCamp/guide-articles#166]
Original poster: @carl-parrish and a link the the issue: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5061

http://www.2ality.com/2015/06/tail-call-optimization.html is a decent explanation as it relates to javascript but honestly the best source I know of explains it for Ruby. http://nithinbekal.com/posts/ruby-tco/

**Comment by brianamarie** [comment]
I think this is definitely a topic that needs to be covered when learning programming and JS, but I'm not sure I can see how it would fit into a short video effectively. It may be better formatted as traditional challenges. 

Did you post this because you'd like to write a script and record these videos, or mainly because you would like to see it covered in the FCC curriculum somewhere? @bugron 

@jameswinegar, do you have any thoughts on this in terms of whether it would be better presented as a video challenge or a traditional challenge?

**Comment by bugron** [comment]
@brianamarie I've only [moved](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/5061#issuecomment-185005051) original issue from FreeCodeCamp repository to this one because this issue is related to Hikes (as a part of big cleanup I was doing in FCC repo that day).

**Comment by brianamarie** [comment]
Okay, thank you @bugron. @carl-parrish could you offer some clarification?

@SaintPeter, looks like you put the hike stamp on it in the other issue. 

My main concern is that this would be better as a written challenge, but I'd love to hear some other opinions. :)

**Comment by brianamarie** [comment]
I'd love to see this moved forward with scripts for video challenges - adding 'help wanted' label.

**Comment by brianamarie** [comment]
### So you want to help with this issue? Great! Keep track of your steps here. 

- [ ] Check out these resources to get ready
  - [ ] [Article with general guidelines](https://medium.freecodecamp.com/let-s-go-for-a-hike-here-s-your-map-4301df6e3801#.f91m4eq85)
  - [ ] [Video challenge chat](https://gitter.im/FreeCodeCamp/hikes)
  - [ ] [Hike repository](https://github.com/FreeCodeCamp/hikes)
- [ ] Find this topic in the [video challenge tracking document](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md). If it's not there, add it where you think it fits best.
- [ ] Make a pull request to assign yourself as an assignee in the [video challenge tracking document](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md).
- [ ] Propose a script as a [markdown file](https://guides.github.com/features/mastering-markdown/) in a Pull Request
  - Create a new branch with `<yourusername-videoname>`
  - Create a new file labeled `<video-title.md>` within the appropriate folder (`scripts/<unit-title>/<video-title.md>`). If that folder doesn't exist yet, create one!
  - Save your changes and open a pull request comparing to master. `@` mention brianamarie for feedback.
- [ ] Record your video
  - Set up a whiteboard and record your video 
- [ ] Comment in your PR with the link to your video. `@` QuincyLarson and brianamarie
  - You'll get feedback, and we'll work with you to help refine the video so we can include it on FreeCodeCamp.com
- [ ] Open a PR in the [Free Code Camp repository](https://github.com/freecodecamp/freecodecamp) including your video links, scripts, and questions to get them added to the site
