### ISSUE TITLE
Networking Improvements

### ISSUE THREAD

**Issue by ZebGirouard** [freeCodeCamp/guide-articles#171]
As a self-taught CCNA and networking enthusiast, I would love to help FCC with a Computer Networking subsection of the Video Series.

Before I get to that, there's an issue I'd like to point out in the Routers and Packets video.  This may be rendered irrelevant if we switch (get it?) that video out and put a more in-depth series together.  However...

Question 3 in the R and P video asks if a data stream can split up packets.  The answer given is yes, but I'm 99% sure that's not correct.  Packets are PDUs (protocol data units) and as such are, by definition, indivisible.  That is not to say that a file, request, etc can't be broken up into different packets.  But the packet itself is a unit, and when integrity checking is done on either end, it must arrive "intact enough" to be considered valid.

Similarly, a frame is not a piece of a packet, it is a layer 2 PDU (packets are layer 3).  A simple, introductory metaphor for FCC is a series of envelopes wrapped around each increasing layer from 1 (0s and 1s) all the way to 7 (application information).  They are wrapped around each other, one after the other, until the signal leaves the originator (usually a computer).  Then they are unwrapped on the other end, one after the other, until the machine can interpret the literal bytecode from layer 1 again.

Sorry for the wordiness, but that will probably play into the lessons I'd like to present.  So without further ado, here's a skeleton from a PPT presentation I have given to friends and colleagues in the past...
1. A Simple Case - Point-to-Point configuration and electrons (0s and 1s) on a wire
2. Onions Have Layers - The envelope metaphor above, plus a description of all 7 layers
3. Layer 2 vs Layer 3 w/ Maps
4. What's in an Address? - Layer 2 (MAC), Layer 3 (IP), Layer 4 (Ports), Binary Review
5. A Complex Case - Routers, Switches, and end-to-end communication

That seems to be the smallest unit I can ever teach without raising all sorts of rabbit-hole questions, but we may want to tweak it to be more relevant to web developers in FCC.  I'm certainly open to changes.

**Comment by ZebGirouard** [comment]
Hm, let's see if I follow.  I could restructure the above into...

Networking Basics
- [ ] 7 Layers of Computer Networking
- [ ] Network Addresses
- [ ] Network Maps

I feel like #1 in my earlier plan was covered well by Briana already, and #3 and #5 can be rolled into a more graphical explanation of networking that (aside from some address labels) wouldn't be really dependent on the other topics.  The 2-minute part will be the tricky one, so I may add another lecture if I start recording and realize I'm condensing too much.

**Comment by ZebGirouard** [comment]
@QuincyLarson , @brianamarie 

Sorry for dropping off there, but I have a month before I start my new job so should have some time to polish off these three videos.

I have assembled what I think is a [solid, yet compact, slide deck](https://docs.google.com/presentation/d/1F0kpMopdLGQNCE7EOREKmKafujEpO6Fl9W5g0ZcYn5A/edit?usp=sharing), and I'll play around with the whiteboard tomorrow to see other ways to present the media.

Feedback is certainly welcome.  I'm looking forward to giving back to FCC, at least a little.

**Comment by ZebGirouard** [comment]
@QuincyLarson @brianamarie ,

You can see my first video here:
https://youtu.be/9-1S5TRUOo8

Please let me know if I'm on the right track, or if you have ideas for improvement.

**Comment by ZebGirouard** [comment]
@QuincyLarson @brianamarie ,

Video number 2 (maps):
https://youtu.be/VZSNUGwW8BE

Video number 3 (addresses):
https://youtu.be/NrDHbW-wgw4

Let me know what I need to fix, and how I might submit this to the FCC site.

**Comment by brianamarie** [comment]
@ZebGirouard Hello! 👋  

Apologies that I haven't been more active in this thread - I'm super impressed at the work you've done!!! I'd love to chat about this on the phone or on skype. I'm going to ping you in Gitter. 😄  🎉 🎈 Thank you so much for contributing this way!

**Comment by atjonathan** [comment]
@ZebGirouard, please make a pull request with the scripts!

**Comment by ZebGirouard** [comment]
I was unclear of the format needed, so I figured I'd submit what I have in READMEs in a "network-engineering" folder inside the "video-categories" directory.  All I have at the moment are my YouTube links and Google Slides (in one README) as well as an unformatted script for each of the three videos (in separate markdown files).  Let me know if this is missing anything.
