### ISSUE TITLE
Proposed Series: Graph Theory Applications

### ISSUE THREAD

**Issue by SEGrooms** [freeCodeCamp/guide-articles#175]
HELP WANTED
I haven't yet studied graph theory and probably won't have enough knowledge to contribute to videos for at least another 6 months.

---

-- = Script not yet completed
/ = Script submitted and ready to record
X = Video is being recorded & edited
√ = Video has been finished and uploaded

**Comment by SEGrooms** [comment]
This would be an excellent topic to cover if @ZebGirouard is going to become completing a series on networks.

**Comment by jameswinegar** [comment]
What is a graph?
Different structures a graph can have.
Why Directed Acyclic Graphs (DAGs) are important?

A lot of ideas can be done here with network analysis. GitHub projects stemming from FCC contributors could be an example.

**Comment by brianamarie** [comment]
### So you want to help with this issue? Great! Keep track of your steps here. 

- [ ] Check out these resources to get ready
  - [ ] [Article with general guidelines](https://medium.freecodecamp.com/let-s-go-for-a-hike-here-s-your-map-4301df6e3801#.f91m4eq85)
  - [ ] [Video challenge chat](https://gitter.im/FreeCodeCamp/hikes)
  - [ ] [Hike repository](https://github.com/FreeCodeCamp/hikes)
- [ ] Find this topic in the [video challenge tracking document](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md). If it's not there, add it where you think it fits best.
- [ ] Make a pull request to assign yourself as an assignee in the [video challenge tracking document](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md).
- [ ] Propose a script as a [markdown file](https://guides.github.com/features/mastering-markdown/) in a Pull Request
  - Create a new branch with `<yourusername-videoname>`
  - Create a new file labeled `<video-title.md>` within the appropriate folder (`scripts/<unit-title>/<video-title.md>`). If that folder doesn't exist yet, create one!
  - Save your changes and open a pull request comparing to master. `@` mention brianamarie for feedback.
- [ ] Record your video
  - Set up a whiteboard and record your video 
- [ ] Comment in your PR with the link to your video. `@` QuincyLarson and brianamarie
  - You'll get feedback, and we'll work with you to help refine the video so we can include it on FreeCodeCamp.com
- [ ] Open a PR in the [Free Code Camp repository](https://github.com/freecodecamp/freecodecamp) including your video links, scripts, and questions to get them added to the site
