### ISSUE TITLE
Lets Talk: Unconscious Bias

### ISSUE THREAD

**Issue by liberaltech** [freeCodeCamp/guide-articles#178]
Lets create a dialogue about the unconscious bias in STEM.
Unconscious bias has long been a dormant problem 

https://www.youtube.com/watch?v=-8H7eeMNfLw

**Comment by brianamarie** [comment]
Hello @liberaltech! Are you posting this issue as a request for a video series, or would you like to help create a video series for Free Code Camp with this topic?

**Comment by brianamarie** [comment]
### So you want to help with this issue? Great! Keep track of your steps here. 

- [ ] Check out these resources to get ready
  - [ ] [Article with general guidelines](https://medium.freecodecamp.com/let-s-go-for-a-hike-here-s-your-map-4301df6e3801#.f91m4eq85)
  - [ ] [Video challenge chat](https://gitter.im/FreeCodeCamp/hikes)
  - [ ] [Hike repository](https://github.com/FreeCodeCamp/hikes)
- [ ] Find this topic in the [video challenge tracking document](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md). If it's not there, add it where you think it fits best.
- [ ] Make a pull request to assign yourself as an assignee in the [video challenge tracking document](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md).
- [ ] Propose a script as a [markdown file](https://guides.github.com/features/mastering-markdown/) in a Pull Request
  - Create a new branch with `<yourusername-videoname>`
  - Create a new file labeled `<video-title.md>` within the appropriate folder (`scripts/<unit-title>/<video-title.md>`). If that folder doesn't exist yet, create one!
  - Save your changes and open a pull request comparing to master. `@` mention brianamarie for feedback.
- [ ] Record your video
  - Set up a whiteboard and record your video 
- [ ] Comment in your PR with the link to your video. `@` QuincyLarson and brianamarie
  - You'll get feedback, and we'll work with you to help refine the video so we can include it on FreeCodeCamp.com
- [ ] Open a PR in the [Free Code Camp repository](https://github.com/freecodecamp/freecodecamp) including your video links, scripts, and questions to get them added to the site

**Comment by liberaltech** [comment]
I would love to help create a video series for FCC!

**Comment by brianamarie** [comment]
@liberaltech That is fantastic! 🎉  As you may be able to tell, this repository is going through some changes and refinements in process. 😄  

To create a video series, these steps are probably the best way to start. Do you have any questions, or is there any way I can help you get started? 

#### 1. Get Ready
- [ ] Check out these resources to get ready
  - [ ] [Article with general guidelines](https://medium.freecodecamp.com/let-s-go-for-a-hike-here-s-your-map-4301df6e3801#.f91m4eq85)
  - [ ] [Video challenge chat](https://gitter.im/FreeCodeCamp/hikes)
  - [ ] [Hike repository](https://github.com/FreeCodeCamp/hikes)

#### 2. Write your Script 
- [ ] [Fork this repository](https://help.github.com/articles/fork-a-repo/) to your personal account 
- [ ] [Create a new branch](https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/) with `<yourusername-videoname>`
- [ ] [Create a new file](https://github.com/blog/1327-creating-files-on-github) labeled `<video-title.md>` within the appropriate folder (`scripts/<unit-title>/<video-title.md>`). If that folder doesn't exist yet, create one! Fill it in with your script for the video challenge.

#### 3. Open a Pull Request
- [ ] Navigate back to the [FreeCodeCamp/hikes repository](https://github.com/freecodecamp/hikes) and  propose a script as a [markdown file](https://guides.github.com/features/mastering-markdown/) in a [Pull Request](https://help.github.com/articles/creating-a-pull-request/).
- [ ] In the body of the pull request, `@` mention brianamarie for feedback, like this: @brianamarie.
