### ISSUE TITLE
 Forking FreeCodeCamp and Series Overview

### ISSUE THREAD

**Issue by Pengoyote** [freeCodeCamp/guide-articles#179]
The video should include everything in [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) article.

Sub-Videos:
- Forking FreeCodeCamp and Series Overview
- Installing Node.JS
- Installing MongoDB
- Installing Git (Multiple videos for different operating systems)
- Installing npm dependencies (Gulp, Bower)
- Getting API keys for example github, facebook, twitter etc. (.env file)
- Various NPM Scripts and their usage
- COM1000 Installation/Setup and Review
- Linter setup on ide’s and editors
- Using Github and its branching and commit standards (Branch Naming)
- How Pull Requests Work (https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md#creating-pull-requests)
- Reference this simple starter site (try.github.io) for learning Git.

Tagging @SaintPeter and @yashdeeph709.

**Comment by SaintPeter** [comment]
This looks like a solid list.  I like the granular breakout, since many of these are good stand-alone topics.

Maybe a video on COM1000 install/setup?

**Comment by yashdeeph709** [comment]
I have started working on the scripts for videos.

**Comment by brianamarie** [comment]
@yashdeeph709 How's it going? Any progress on scripts for these videos?

**Comment by brianamarie** [comment]
### Keep track of your steps here. 

- [ ] Check out these resources to get ready
  - [ ] [Article with general guidelines](https://medium.freecodecamp.com/let-s-go-for-a-hike-here-s-your-map-4301df6e3801#.f91m4eq85)
  - [ ] [Video challenge chat](https://gitter.im/FreeCodeCamp/hikes)
  - [ ] [Hike repository](https://github.com/FreeCodeCamp/hikes)
- [ ] Find this topic in the [video challenge tracking document](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md). If it's not there, add it where you think it fits best.
- [ ] Make a pull request to assign yourself as an assignee in the [video challenge tracking document](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md).
- [ ] Propose a script as a [markdown file](https://guides.github.com/features/mastering-markdown/) in a Pull Request
  - Create a new branch with `<yourusername-videoname>`
  - Create a new file labeled `<video-title.md>` within the appropriate folder (`scripts/<unit-title>/<video-title.md>`). If that folder doesn't exist yet, create one!
  - Save your changes and open a pull request comparing to master. `@` mention brianamarie for feedback.
- [ ] Record your video
  - Set up a whiteboard and record your video 
- [ ] Comment in your PR with the link to your video. `@` QuincyLarson and brianamarie
  - You'll get feedback, and we'll work with you to help refine the video so we can include it on FreeCodeCamp.com
- [ ] Open a PR in the [Free Code Camp repository](https://github.com/freecodecamp/freecodecamp) including your video links, scripts, and questions to get them added to the site

**Comment by atjonathan** [comment]
@yashdeeph709 I'm switching this back to `01: Help Wanted` due to inactivity, let us know if you are still up for it :+1:

**Comment by QuincyLarson** [comment]
@atjonathan this is a great idea. I've created sub-issues for each of these videos and renamed this to the "series overview" challenge.

**Comment by brianamarie** [comment]
@QuincyLarson I'm going to un-assign myself from this and move it back to `01: Help Wanted`. I think these videos may be better to do as a mix of whiteboard/computer screen to show the process.
