### ISSUE TITLE
Proposed Series: Gamification 

### ISSUE THREAD

**Issue by SolarDifference** [freeCodeCamp/guide-articles#181]
I'm completely new to this so some feedback would be appreciated. Over the next few months I'll be working on developing a video series for gamification. This may have some overlap with the game development and UX experience design series as well. So if you're working on those, I'd appreciate your feedback on this. 

For those less familiar with gamification, I've attached two relevant articles. The first is one I published a few years ago for a specific academic audience, and the second is widely considered a seminal treatise on the topic. 

[Morford, Witts, Killingsworth, & Alavosius (2014).pdf](https://github.com/FreeCodeCamp/hikes/files/245244/Morford.Witts.Killingsworth.Alavosius.2014.pdf)
[Deterding et al (2011).pdf](https://github.com/FreeCodeCamp/hikes/files/245245/Deterding.et.al.2011.pdf)

Also, I'll be using the following notation (per SEGrooms) to indicate my progress:

-- = Script not yet completed
/ = Script submitted and ready to record
X = Video is being recorded & edited
√ = Video has been finished and uploaded

Currently proposed videos:

-- What is Gamification?
-- Game Design Elements: Part 1
-- Game Design Elements: Part 2
-- The Science Supporting Gamification
-- Examples of Gamification

**Comment by brianamarie** [comment]
@SolarDifference 👋  Hello!

I apologize for the delay in getting back to you - I'm so excited to see this post and your interested in contributing to the video challenges! 

Are you still interested in helping with this series? 🙏

**Comment by brianamarie** [comment]
### Keep track of your steps here. 

- [ ] Check out these resources to get ready
  - [ ] [Article with general guidelines](https://medium.freecodecamp.com/let-s-go-for-a-hike-here-s-your-map-4301df6e3801#.f91m4eq85)
  - [ ] [Video challenge chat](https://gitter.im/FreeCodeCamp/hikes)
  - [ ] [Hike repository](https://github.com/FreeCodeCamp/hikes)
- [ ] Find this topic in the [video challenge tracking document](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md). If it's not there, add it where you think it fits best.
- [ ] Make a pull request to assign yourself as an assignee in the [video challenge tracking document](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md).
- [ ] Propose a script as a [markdown file](https://guides.github.com/features/mastering-markdown/) in a Pull Request
  - Create a new branch with `<yourusername-videoname>`
  - Create a new file labeled `<video-title.md>` within the appropriate folder (`scripts/<unit-title>/<video-title.md>`). If that folder doesn't exist yet, create one!
  - Save your changes and open a pull request comparing to master. `@` mention brianamarie for feedback.
- [ ] Record your video
  - Set up a whiteboard and record your video 
- [ ] Comment in your PR with the link to your video. `@` QuincyLarson and brianamarie
  - You'll get feedback, and we'll work with you to help refine the video so we can include it on FreeCodeCamp.com
- [ ] Open a PR in the [Free Code Camp repository](https://github.com/freecodecamp/freecodecamp) including your video links, scripts, and questions to get them added to the site

**Comment by SEGrooms** [comment]
Really like the idea of this series. It's becoming almost standard for educational sites. Even FCC has elements of gamification in form of jokes. Whether they be subtle, or in your face by saying, "Honey badger don't care!" It makes the process a lot more enjoyable.

**Comment by SolarDifference** [comment]
@brianamarie I'm just as guilty for delaying my response! Yes I'm still interested in working on this. I won't really be able to get to it until mid August or early September. In the meantime I'll look through the materials you sent me and look at some of your videos as exemplars.

**Comment by brianamarie** [comment]
@SolarDifference Awesome. 😄 If there's anything you need along the way, please feel free to ping me (and also @atjonathan or @SEGrooms).

**Comment by QuincyLarson** [comment]
@SolarDifference When you get a chance to start working on this, please break this issue up into sub-issues for each video and for each of them, use the Gamification tag. This will make it much easier for us to track the progress of each individual video.
