### ISSUE TITLE
Kilobyte vs Kibibyte

### ISSUE THREAD

**Issue by RainbowDangerDash** [freeCodeCamp/guide-articles#192]
In (this)[https://www.freecodecamp.com/videos/computer-basics-how-to-measure-data-size] video summary

it is stated that a kilobyte is 1024 bytes, which is incorrect
according to SI's definition, in which Kilo = 1000;

So, Kilobyte = 1000 b
Kibibyte = 1024 b

https://en.wikipedia.org/wiki/Kibibyte

It might be good to inform users of these terms in order for them to
not look confused when they hear it, or when they buy their 16 GB
disk, only for Windows to tell them it's 14.9 GiB!

**Comment by atjonathan** [comment]
Thanks for catching this!

**Comment by brianamarie** [comment]
@atjonathan @RainbowDangerDash Thank you! Ideally, this will be corrected if/when we have the chance to re-record the videos. In the meantime, do you think an acceptable compromise would be to make a note of this in the video description?

@Septimus Do you have thoughts/suggestions on this?

**Comment by Septimus** [comment]
I think making a note on the video would be a great compromise for the time being. Then when I create the new videos covering similar topics this will be corrected. :) @brianamarie @RainbowDangerDash @atjonathan
