### ISSUE TITLE
Introduction to P VS NP

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide-articles#208]
https://en.wikipedia.org/wiki/P_versus_NP_problem

**Comment by erictleung** [comment]
This is a really good lecture of complexity https://www.youtube.com/watch?v=moPtwq_cVH8

**Comment by SEGrooms** [comment]
**Incredibly** excited for this series!

**Comment by brianamarie** [comment]
## Introduction to P vs NP

#### Context
- P and NP are ways to classify and sort equations, algorithms, problems that we would try to have a computer solve
- "P" represents questions that are fast to solve
- "NP" represents questions that aren't fast to solve, but are fast to check
  - like sudoku 
  - traveling salesman problem
- Boils down to question: If there is a fast way to check the solution to a problem, does it also mean there is a fast way to solve it? 

#### Why does P vs NP matter?
- Computers already do so much - but if we can figure out how to solve problems by knowing that we can check solutions quickly, how much more can we do? 
- What problems aren't being solved by computers that could be?
