### ISSUE TITLE
Introduction to Markdown

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide-articles#21]

**Comment by swheatley** [comment]
Interested in working on this

**Comment by brianamarie** [comment]
@swheatley 😄 👋 🎉 

### So you want to help with this issue? Great! Keep track of your steps here. 

- [ ] Check out these resources to get ready
  - [ ] [Article with general guidelines](https://medium.freecodecamp.com/let-s-go-for-a-hike-here-s-your-map-4301df6e3801#.f91m4eq85)
  - [ ] [Video challenge chat](https://gitter.im/FreeCodeCamp/hikes)
  - [ ] [Hike repository](https://github.com/FreeCodeCamp/hikes)
- [ ] Find this topic in the [video challenge tracking document](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md). If it's not there, add it where you think it fits best.
- [ ] Make a pull request to assign yourself as an assignee in the [video challenge tracking document](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md).
- [ ] Propose a script as a [markdown file](https://guides.github.com/features/mastering-markdown/) in a Pull Request
  - Create a new branch with `<yourusername-videoname>`
  - Create a new file labeled `<video-title.md>` within the appropriate folder (`scripts/<unit-title>/<video-title.md>`). If that folder doesn't exist yet, create one!
  - Save your changes and open a pull request comparing to master. `@` mention brianamarie for feedback.
- [ ] Record your video
  - Set up a whiteboard and record your video 
- [ ] Comment in your PR with the link to your video. `@` QuincyLarson and brianamarie
  - You'll get feedback, and we'll work with you to help refine the video so we can include it on FreeCodeCamp.com
- [ ] Open a PR in the [Free Code Camp repository](https://github.com/freecodecamp/freecodecamp) including your video links, scripts, and questions to get them added to the site

**Comment by brianamarie** [comment]
# Markdown

### What is Markdown?
- Way to format text
- Simple, code-like syntax
- Stored in `.md` text files

### When do I use it?
- On GitHub
- Many other sites are adopting markdown syntax
- Want to make your text easier to read 

### How do I learn? 
- Using toolbar on GitHub issues, pull requests, and comments
- Many guides online

### A few tips and tricks
- `#` Header 1
- `###` Header 3
- `-` Bullet list
- `:` Emojis
