### ISSUE TITLE
Introduction To "Ethical Hacking"

### ISSUE THREAD

**Issue by mrpatil007** [freeCodeCamp/guide-articles#212]
# **Core Ethical Hacking**
### **The Curriculum for Ethical Hacking core is Follows :**

```
   1.  Introduction To "Ethical Hacking"
   2.  Networking & Basics 
   3.  Foot Printing and reconnaissance
   4.  Scanning
   5.  Windows Hacking
   6.  Trojans & Back-doors
   7.  Proxy & Packet Filtering
   8.  Denial of Service (Dos and DDos Attacks)
   9.  Social Engineering
  10. Stenography
  11. Cryptography
```
### **Description of content:**

```
  The Videos is All About **Ethical Hacking** and **Cyber Security** 
```
- [x] **1.  Introduction To "Ethical Hacking" :** In this Video we can give the overlook of what is      Ethical Hacking is about and what are the opportunities of being a hacker in the IT Era. and also the various types of Hackers.

The following all have their own issues under the "Ethical Hacking" label:
- **2. Networking & Basics :** In this Video we can give the Short Information of Networking and there Basic Needs For Doing Hacking that's Cover In this Section.
- **3. Foot Printing and Reconnaissance :** In this Video We can give the Information for how to gather the Information of Target System and the types of Information Gathering Like passive, active, or Anonymous and etc and also cover What is Meant by Vulnerabilities ? .
- **4. Scanning :** In this Section we provide the information about How to Scan Ports ? Using Various tools like Nmap, Superscan and etc and Also Give the Information about Enumeration. 
- **5. Windows Hacking :** Oh Here We talk about the New Vulnerabilities of Windows and also if you forget your system password then how to Break the System Password of Windows System in Various Way's. and also know How to prevent from Hacker's to break Our Windows System 
- **6. Trojans & Back-doors :** Here we cover What Trojans and Back-doors is ? and there types. How Trojans and back-doors are work to receive and send data From the target system to the attacker. and how to prevent Trojans and back-doors ?. this topics will be cover in this section.
- **7. Proxy & Packet Filtering :**  In This Section we give information about Proxy. and How Proxy works. How to Filter Packet using Wireshark and How to Analyze them.      
- **8. Denial of Service (Dos and DDos Attacks) :** Wala in this Section we provide the information of Dos and DDos Attacks How they Works ? and How to Prevent from them.
- **9. Social Engineering :** In this Section we cover various types Social Engineering attacks like Session hijacking,, Tab napping, Phishing and How to Prevent From them.
- **10. Stenography :** In this Section we would talk about What is Stenography ?. Give Information on Case Studies of Stenography. How make a Steno hack ?.
- **11. Cryptography :** In Cryptography Section we Provide Information about various algorithms of Cryptography. How Hackers use Cryptography for Conversion's. How to Decrypt and Encrypt it ?.  

![02: Scripting](https://img.shields.io/badge/Label-02: Scripting-000000.svg)

**Comment by atjonathan** [comment]
@mrpatil007 thanks very much for taking this up, I'm very excited for this series!

**Comment by mrpatil007** [comment]
@atjonathan I have Updated the detailed descriptions of each video. Please Check that and Help to Improve it and i was thinking to about to make a section on Advance Ethical Hacking also where all other advance hacks will be cover. :)

**Comment by mrpatil007** [comment]
@atjonathan What you think about this curriculum structure ?

**Comment by atjonathan** [comment]
@mrpatil007 I think that's awesome :+1: 
I say the scripting can start :tada:

**Comment by mrpatil007** [comment]
@atjonathan yup first i PR Something Related to this. and tomorrow i will plan to record first introduction video.

**Comment by mrpatil007** [comment]
@atjonathan  hey first video is complete but where i upload the first video :)

**Comment by atjonathan** [comment]
@mrpatil007, upload it to your channel temporarily and send us the link.

**Comment by mrpatil007** [comment]
@atjonathan ok

**Comment by QuincyLarson** [comment]
@mrpatil007 Awesome! I'm excited to see it! 

Could you break each video down into its own issue? That way we can have more granular control of each of their status.

**Comment by mrpatil007** [comment]
@QuincyLarson ya sure

**Comment by QuincyLarson** [comment]
@mrpatil007 I'm doing this for all the other issues, so I've gone ahead and done this for these. 

You can see all the issues here: https://github.com/FreeCodeCamp/hikes/labels/Ethical%20Hacking

I've changed the title of this issue to the "intro to ethical hacking" challenge to preserve its comment history.

Good luck getting these scripted and recorded. If I can be of any help, let me know :)
