### ISSUE TITLE
Ethical Hacking Series Video 1 Introduction to Ethical Hacking Progress

### ISSUE THREAD

**Issue by mrpatil007** [freeCodeCamp/guide-articles#216]
**Ethical Hacking Series Video 1 - Introduction to Ethical Hacking  Progress**
       First Introduction video is on the way of recording 

 ![03: Recording](https://img.shields.io/badge/Label-03: Recording-000000.svg)

**Comment by atjonathan** [comment]
@mrpatil007, once you have finished recording this video, please post the link to your video which we will review. Once we have finalised the details, we will post it on our own channel!

**Comment by atjonathan** [comment]
@mrpatil007, any update on this?
