### ISSUE TITLE
Logic: Conditional & Biconditional Statements

### ISSUE THREAD

**Issue by SEGrooms** [freeCodeCamp/guide-articles#233]

**Comment by SEGrooms** [comment]
@QuincyLarson when this video is complete, I believe it would be appropriate publish the videos I've created so far.

**Comment by QuincyLarson** [comment]
Awesome! I remember both of these concepts from philosophy class. Stoked to watch these videos.

**Comment by SEGrooms** [comment]
changing to definitions **only**
