### ISSUE TITLE
Using the Unix/Linux Command Line

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide-articles#24]

**Comment by Oxyrus** [comment]
I'd love to help out with this.

**Comment by brianamarie** [comment]
@Oxyrus That's fantastic!!! 🎉 Would you be interested in creating a script, recording a video, or both? (P.S. if you haven't already, check out the [README.md](https://github.com/FreeCodeCamp/hikes/blob/master/README.md) if you haven't already 😄 )

**Comment by Oxyrus** [comment]
@brianamarie in creating a script, I'm not personally great in front of a camera :P

**Comment by brianamarie** [comment]
@Oxyrus Hey, you never know! 😉 

Either way, that's fantastic!!! I will mark this issue to 'scripting'. The README.md should give instructions on how to go about creating a pull request with a proposed script. Please let me know if you have any questions along the way, and thank you for doing this! 🎉

**Comment by Oxyrus** [comment]
@brianamarie how long should the script be?

**Comment by brianamarie** [comment]
@Oxyrus The goal is that the script will be turned into a video that will last between 1-3 minutes.
