### ISSUE TITLE
Logic: What Is A Fallacy?

### ISSUE THREAD

**Issue by SEGrooms** [freeCodeCamp/guide-articles#261]
- define fallacy: contradiction, fallacy of the converse, fallacy of the inverse

**Comment by SEGrooms** [comment]
@QuincyLarson @Septimus @brianamarie This issue will be closed next week. When it is closed, I believe this is a large enough chunk of knowledge to upload to FCC! :)

**Comment by SEGrooms** [comment]
![alt text](https://media.giphy.com/media/4c4jQPdVv381G/giphy.gif "Dance Party")

**Comment by SEGrooms** [comment]
Just saying, I'm pretty excited!!!!

**Comment by QuincyLarson** [comment]
@SEGrooms awesome! I'm excited about this video. You could probably record a dozen videos about all the logical fallacies out there, there are so many!

By the way, great gif. I hadn't seen that before.

**Comment by SEGrooms** [comment]
OOH!!! I'm going to add a video on knights and knaves!!

**Comment by SEGrooms** [comment]
https://en.wikipedia.org/wiki/Knights_and_Knaves If you want good books on logic, you can't go wrong with Charles Dodgson.

**Comment by QuincyLarson** [comment]
@SEGrooms awesome! That would be really interesting. There are lots of logic puzzles you could cover. Also, you might consider the Monty Hall problem :)

**Comment by SEGrooms** [comment]
@QuincyLarson also a good idea! That would be nice, because it is probably the most popular logic problem.

**Comment by SEGrooms** [comment]
I'm merging this with #259 and renaming "What Are Tautologies & Fallacies?". The extra fun logic problems will have their own videos. I believe riddles are the best way to truly test your logic skills.
