### ISSUE TITLE
Computer Science problems that are P

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide-articles#292]

**Comment by brianamarie** [comment]
## P vs NP: Problems that are 'P'

#### Overview of P vs NP 
- Asks whether every problem whose solution can be quickly verified by a computer can also be quickly solved by a computer.
- P problems _can_ be solved quickly by a computer
- NP problems _can not_ be solved quickly by a computer, but they can be checked quickly by a computer.

#### Examples of questions that are P
- Arithmetic 
- Calculating the greatest common divisor
- Factorial calculation
- Sorting of array elements
- Every bonfire on Free Code Camp can be solved by a 'P' solution (@QuincyLarson is that true?) 

#### Why those are P
- Computers can go through those problems in a set amount of time
- It's OK to ask computers to do these things with algorithms, we know they can handle it

#### Why does that matter? 
- When you are solving a problem, if you can solve it with clearly defined, simple to execute functions, you will be writing a faster program. 
- Try break down your problem into smaller functions that are all P problems
