### ISSUE TITLE
Computer Science problems that are NP

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide-articles#293]

**Comment by brianamarie** [comment]
## P vs NP: Problems that are NP

#### Review
- 'P', for polynomial time, is a class of problems that can be solved quickly by a computer 
- 'NP', non polynomial time, is a class of problems that cannot be solved quickly but can be checked quickly if a given answer is correct

#### Examples of NP problems
- Puzzles
- Sudoku
- Word problems
