### ISSUE TITLE
Computer Science problems that are NP Hard

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide-articles#294]

**Comment by brianamarie** [comment]
## P vs NP: NP Hard Problems

#### Review
- We are discussing a type of 'NP' problem, or problems that can't be solved in polynomial time. AKA hard for computers to solve quickly.
- NP problems CAN be checked quickly for correctness, like a sudoku puzzle or crossword. 
- However, there are more ways to break down NP classification of problems.

#### NP hard
- Working definition, a way to compare difficulty of NP problems
- A problem is NP hard is at least as hard as a catalogue of very difficult problems 
- It is thought that it is the same level of difficulty, but not mathematically proved to be as difficult
