### ISSUE TITLE
NP Completeness

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide-articles#295]

**Comment by brianamarie** [comment]
## P vs NP: NP Completeness

#### Review
- We've covered 
  - P (simple problems for computers)
  - NP (problems that aren't easy for computers to solve, but are easy for computers to check)
  - NP Hard (problems that are decidedly as difficult as a certain other class of problems)

#### NP Complete 
- An NP complete problem's solution can solve any other problem that exists in the NP class.  
- 2 ways to show an NP problem is NP Complete
  - Take another NP complete problem and reduce/compare it to your problem
  - Mathematically prove that your problem contains the solution to any other problem in NP

#### Recap: Why does this matter? 
- As you try to solve problems with code, you may be faced with some very difficult ones, like the traveling salesman problem. 
- Knowing the class of these problems may help you find an approach that you're satisfied with, or give you a basis for researching previous attempts at solving them
- And, you can join arguments on whether NP problems are just P problems we're not smart enough to solve yet, or if they're two distinct things 😉
