### ISSUE TITLE
What is an API?

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide-articles#30]

**Comment by highlanderkev** [comment]
API stands for Application Programming Interface. The term gets wildly used and applied to many different situations in software engineering but generally refers to an agreement or contract which defines how to interact with a certain system or software. This interaction may include requirements for input, definitions about possible output, high-level functional details and/or differences between versions. Typical examples of API's include: builtin programming language class definitions that extend primitives and provide greater functionality; web server's which act as data sources for client facing applications; utility libraries or software dependencies that provide additional functionality to the application.

Typically, it is good practice in software design to program to an interface, not an implementation. Doing so generally helps with future maintenance and refactoring. The idea behind this being that code and implementation details often change but the business requirements typically stay the same (or so you hope). 

API's are also very important/relevant to the rise and use of Micro-service architectures. The idea being that each independent (micro) service implements it's own API which other services or client endpoints use and consume, decoupling specific implementations from each other and providing for greater flexibility in design.

**Comment by venegu** [comment]
Cool answer, I can also make this video is no one has take the time to do it :smile:!

**Comment by brianamarie** [comment]
@highlanderkev Awesome! I am going to re-format your text a little and maybe use it for a script to record in the near future. 😄

**Comment by brianamarie** [comment]
## What is an API?

#### When will you use an API?
- At FCC, you may use APIs in the front end development projects. 
- I used an API to get the weather for a certain area
- APIs are widely used in web development, and serve as a channel for services and developers to communicate information quickly and in a way that fits each developer's needs

#### Basic Definition of API
- API - Application Programming Interface
- The term API is wildly used, but generally refers to an agreement or contract which defines how to interact with a certain system or software. 
- This interaction may include requirements for input, definitions about possible output, high-level functional details and/or differences between versions. 

#### API Examples 
- Builtin programming language class definitions
- Web servers which act as data sources for client facing applications (like my weather API function)
- Utility libraries or software dependencies that provide additional functionality to the application.
- Google maps has an API, GitHub has an API - most sites that store, sort, or create data will have some type of API 

#### Recap
- APIs provide handy access to lots of information
- You can use APIs to display, sort, or gather data
