### ISSUE TITLE
What is Object Oriented Programming?

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide-articles#34]

**Comment by PizzaPokerGuy** [comment]
I would love to do this.

**Comment by brianamarie** [comment]
@PizzaPokerGuy I'm so thrilled to see your comments on this issue and some of the other issues! 🎉 💯 

As with the others, if you have any questions or if you need help getting started with the [steps in the README.md](https://github.com/FreeCodeCamp/hikes/blob/master/README.md), let me know. Should I add the 'scripting' label?
