### ISSUE TITLE
Why comment your code?

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide-articles#35]

**Comment by PizzaPokerGuy** [comment]
I would love to make a quick video showcasing this.

**Comment by brianamarie** [comment]
@PizzaPokerGuy Fantastic!!! Thank you! 😄 

If you have any questions or if you need help getting started with the [steps in the README.md](https://github.com/FreeCodeCamp/hikes/blob/master/README.md), let me know. Should I add the 'scripting' label?
