### ISSUE TITLE
Linear Algebra: What Is A Vector?

### ISSUE THREAD

**Issue by SEGrooms** [freeCodeCamp/guide-articles#415]

**Comment by dapperAuteur** [comment]
I'm going to submit a script today.

**Comment by SEGrooms** [comment]
Awesome! I look forward to reading it! 👍

**Comment by dapperAuteur** [comment]
Script draft 0001:
Linear Algebra: What is a vector?

Hello campers,
I'm Anthony also known as dapperAuteur on freeCodeCamp and GitHub.
And thank you for joining me on this short hike about ‘linear algebra: What is a vector?’ 
You're probably familiar with vectors but don't use the word vector to describe it. 
For instance, when the officer asks how fast you were going and you say I don't know. And the officer replies you were doing 15 mph in a school zone. Which isn't a crime. The officer is describing your magnitude. Every vector has a magnitude. 15 mph is a scalar, a number. A vector needs scalar, a number, and a direction. Had the officer said you were going 15 mph and headed East. That's a vector. 2,000 leagues is not a vector. 2,000 leagues South (under the sea) is a vector. You may perform mathematical functions with vectors. Add, subtract, multiply and divide. (Point to white board and each example problem. The whit will contain math problems and a graph).  This graph shows how to draw a vector in a two-dimensional space. Vectors can exist in multi-dimensional spaces, dimensions of much more than two.  

Thank you for joining me, dapperAuteur,  on this freeCodeCamp hike about ‘linear algebra: What is a vector?’

Please stay tuned for the short quiz afterwards.
Thank you.

t/f 
Is this a vector: 45 miles South 
T
Is this a vector: 15 ft
F
You can not add vectors. 
F
You can perform multiplication with vectors. 
T
Is this a vector: North
F

**Comment by SEGrooms** [comment]
I recommend explicitly stating that both a number and magnitude are scalar quantities. You start by talking about magnitude and switch the vocabulary to scalars, which I think may throw people off. Other than that it looks good!

**Comment by dapperAuteur** [comment]
Thank you. I'll make the adjustments.

**Comment by dapperAuteur** [comment]
Script draft 0001:
Linear Algebra: What is a vector?

Hello campers,
I'm Anthony, also known as dapperAuteur on freeCodeCamp and GitHub.
And thank you for joining me on this short hike about ‘linear algebra: What is a vector?’ 
You're probably familiar with vectors but don't use the word vector to describe it. 
For instance, when the officer asks how fast you were going and you say I don't know. And the officer replies you were doing 15 mph in a school zone. Which isn't a crime. The officer is describing your magnitude. Every vector has a magnitude and a direction. 100 feet to the right is a vector. 5 miles South is a vector. 15 mph is a scalar, a number. A vector needs scalar, a number, and a direction; North, South, East, West, Left, Right, Up, Down. Had the officer said you were going 15 mph and headed East. That's a vector. 2,000 leagues is not a vector. 2,000 leagues South (under the sea) is a vector. You may perform mathematical functions with vectors. Add, subtract, multiply and divide. (Point to white board and each example problem. The whiteboard will contain math problems and a graph). This graph shows how to draw a vector in a two-dimensional space. Vectors can exist in multi-dimensional spaces, dimensions of much more than two.

Thank you for joining me, dapperAuteur, on this freeCodeCamp hike about ‘linear algebra: What is a vector?’

Please stay tuned for the short quiz afterward.
Thank you.

t/f 
Is this a vector: 45 miles South 
T
Is this a vector: 15 ft
F
You can not add vectors. 
F
You can perform multiplication with vectors. 
T
Is this a vector: North
F

**Comment by dapperAuteur** [comment]
I have time to film it today once the script is approved.

**Comment by SEGrooms** [comment]
Looks good to me! Let me know if you want any help. I'm going to be recording videos today too, so I'll be by my computer.

**Comment by dapperAuteur** [comment]
Link to download video file:
https://drive.google.com/file/d/0B24K2ovaSJIuUVdMMFIyNjN0RFE/view?usp=sharing
Script draft 0003 editted:
Linear Algebra: What is a vector?

Hello campers,
I'm Anthony, also known as dapperAuteur on freeCodeCamp and GitHub.
Thank you for joining me on this short hike about ‘linear algebra: What is a vector?’ 
You're probably already familiar with vectors but don't use the word vector to describe it. 
For instance, if you're driving and an officer asks how fast you were going and you say I don't know. And the officer replies you were doing 15 mph in a school zone. Which I don't believe is a crime, but I'm sure that's not a vector. Had the officer said you're going 15 mpg East, that is a vector. 2,000 leagues is not a vector. 2,000 leagues South (under the sea) is a vector. 5 feet to the right is a vector. A vector needs a magnitude and a direction. 15 mph is your magnitude. East is your direction. You can perform mathematical computations on a vector. (Point to white board and each example problem. The whiteboard will contain math problems and a graph). You can draw them in a two-dimensional space. Vectors also exist in multi-dimensional spaces, much more than two dimensions. A vector needs a magnitude and a direction. And you can do math with them.

Thank you for joining me Anthony, also known as dapperAuteur on freeCodeCamp and GitHub on this short hike about ‘linear algebra: What is a vector?’

Please stay tuned for the short quiz afterward.
Thank you.

t/f 
Is this a vector: 45 miles South 
T
Is this a vector: 15 ft
F
You can not add vectors. 
F
You can perform multiplication with vectors. 
T
Is this a vector: North
F

**Comment by dapperAuteur** [comment]
New video
https://drive.google.com/file/d/0B24K2ovaSJIuRHhyN2xLWkpUTDA/view?usp=sharing

**Comment by atjonathan** [comment]
@dapperAuteur, this looks cool! Is there anyway you can eliminate the background noise? It's quite distracting. The original video had a slight improvement. The video quality is great, so nothing needs to happen there!

Please open a pull request as mentioned in the [README](https://github.com/FreeCodeCamp/hikes/blob/master/README.md)!

Tagging @QuincyLarson, @brianamarie for review.

**Comment by SEGrooms** [comment]
@dapperAuteur here's my 2 cents.

Improvements
- People will definitely comment on the noise.
- The background is beautiful, but the board should be taking up most of the camera.
- At 0:56 you talk about vector notation:
   - Since A is a column vector, convention says it should be lowercase with an arrow over it.
      - The same is true for B.
   - Currently, since C isn't equal to (3,1), you are defining a point rather than a row vector. This will again be alleviated letting C be lowercase and putting an arrow over it.
   - I recommend introducing component notation even if you have no plans of using them. However, this would probably be a topic for another video.

The Good
- You seemed natural in front of the camera this time! 😄 
- The graph was a nice addition 👍

Linear Algebra is notorious for being notationally dense, so don't let this discourage you! Are you planning to complete a video on addition and subtraction next?

**Comment by dapperAuteur** [comment]
I can do a separate video on vector computations (addition and subtraction). I think multiplication and division would warrant a separate video.
I can make the changes to the current video and resubmit.

**Comment by SEGrooms** [comment]
Yeah, you could pretty easily fit addition and subtraction in the same video. A video on scalar and matrix multiplication, and this would be a good point to introduce abstract notation (i.e. a_ij). By division do you mean scalars or inversion?

**Comment by QuincyLarson** [comment]
@dapperAuteur Awesome! I agree that his is better than the previous version.

I agree with the feedback from @SEGrooms and @atjonathan as well. 

I also agree with you that you should break these down into as many modular videos as necessary.

A couple points:

- please don't add text to the video. @atjonathan will add a bezel for the thumbnail. 
- please introduce yourself Quickly "Hi I'm Anthony with Free Code Camp" and only at the beginning of the video. We can link to your Free Code Camp profile in the description.
This way the video could be a bit shorter - perhaps only a minute - since it's only introducing a few basic concepts.
- We have stopped using the jargon "hikes" so please don't mention it as it may confuse viewers.

Keep in mind that campers will watch many of these videos back-to-back, so you can be as brief as possible. But your delivery is confident, and should be clear to non-native English speakers as well, which is a huge plus!

I also enjoyed your analogies. These are helpful for retaining the information.

**Comment by dapperAuteur** [comment]
Here are the links to the script and video of the latest version of the video. Thank you for your feedback on the previous versions.

[Script](https://docs.google.com/document/d/106JoCb2MtdZ8eRHu_VnT4_KzPvNu94kWLC3SySe_nTo/edit?usp=sharing)

[Video](https://youtu.be/ShFHr88pVJA)

Let me know what you think.

**Comment by atjonathan** [comment]
@dapperAuteur, looks good to me 👍 I might remove the "stay tuned for a short quiz part". You could easily cut the video after without having to re-shoot 😄. This is because our YouTube Channel won't have the quiz!
Tagging @SEGrooms @QuincyLarson

**Comment by dapperAuteur** [comment]
https://youtu.be/rWrffuPe_HE

**Comment by QuincyLarson** [comment]
@dapperAuteur this is great. It is a bit long, though (we aim for 2 minutes or less). 

Since this is such a short video, I don't think we need a recap at the end - I think we could fade out at 2:13, which has a natural break. The next video will load, and you could quickly recap then.

@atjonathan what are your thoughts on this?

**Comment by SEGrooms** [comment]
@dapperAuteur this was a much better position for the white board! 👍  Also, remember this is a video that people can rewind. Meaning, you can talk faster than a normal classroom setting, and you don't need to recap. You should easily be able to make a video in under 2 minutes, as you gave a pretty concise explanation. 👍 👍 

Other than the video length, my only big issue when you mention unit vectors. A unit vector will always yield magnitude of 1. So in the real plane, b-hat could only be equal to [1,0] or [0,1], which we would call i-hat or j-hat respectively. Something similar is called the "normalized vector," which is the unit vector in the direction of the same vector.

For example, let **a** = [4,3], then **a-hat** would be called a normalized vector in general, or the unit vector specific to **a**. That is, **a-hat** is the unit vector in the direct of **a**. Furthermore,  the normalized vector of **a** is defined as **a** divided by its magnitude.

That is, **a-hat** =  **a**/ ||**a**||.
e.g. Let **a** = [4,3], then **a-hat** = [4,3] / √(4**2 + 5**2) = [4,3] / 5 = [0.8, 0.6]. Since this is a unit vector, we can check our work by showing the magnitude of **a-hat** = 1.
i.e. **a-hat** = √(0.8**2 + 0.6**2) = √(0.64 + 0.36) = √(1) = 1, success! 🎉 

I think it's clear that unit vectors deserve their own video. But, if you simply switch b-hat with a row vector b-arrow = (2,1) then you will be all set. Previously, I didn't want you to have (2,1) because you didn't set b-arrow equal to (2,1), meaning it was being referred to as a point rather than a vector.

I apologize for the super lengthy response, but I hope it helped!

**Comment by QuincyLarson** [comment]
@dapperAuteur based on this feedback from @SEGrooms I recommend you record it. 

I know that you've already recorded it at least twice, but each time we are learning a ton and it's steadily improving. The end product will be worth the effort. Thousands of people will ultimately watch this.

**Comment by dapperAuteur** [comment]
I made two versions today. Let me know if one of them meets the requirements for our needs. I appreciate the opportunity to participate and your patience with me on creating these. I'll have time over the holidays to make more or redo this one if necessary.
Video 1: https://youtu.be/RsJLoMtNE3E
Video 2: https://youtu.be/CJbQPLfeZos
