### ISSUE TITLE
Linear Algebra: Matrix Algebra

### ISSUE THREAD

**Issue by SEGrooms** [freeCodeCamp/guide-articles#416]

**Comment by mibrkelly** [comment]
We can use vectors to keep information organized. For example, suppose Alice, Bob and Carl go to the grocery store to buy peaches. If Alice buys 3 peaches, Bob buys 2 peaches, and Carl buys 7 peaches we can keep track of the information as follows:

(A B C) (3 2 7)T (P)

Where A stands for Alice, B stands for Bob, and C stands for Carl. The P is for peaches.

It looks funny, but some mathematicians decided to write it that way a long time ago.

Alice wants more than just peaches though. Besides 3 peaches, suppose Alice buys 5 yams and 1 zucchini. We can keep track of what Alice buys with

(A) (3 5 1) (P Y Z)T

How would we keep track of the number of peaches, yams and zucchinis that Alice, Bob and Carl buy? There is too much information for a vector. See if you can figure it out from the following:

              (3 5 1)
(A B C)  (2 1 0) (P Y Z)T
              (7 2 3)

See that first column, that shows the number of peaches each person bought. See the first row, that shows the fruit that Alice bought. What does the 0 represent? If you said Bob bought 0 zucchini, then you are catching on!

All the information is in one matrix.

(3 5 1)
(2 1 0)
(7 2 3)

Let's say Alice and Bob each go back and buy more fruit. Alice buys 3 more peaches, and Bob decides he would like 2 zucchini after all. How much more fruit did they buy? We can write it with this matrix.

(3 0 0)
(0 0 2)
(0 0 0)

To find the total fruit they bought, we can add the matrices together. We add coordinate by coordinate.

(3 5 1)        (3 0 0)       (3+3  5       1)       (6 5 1)
(2 1 0)   +   (0 0 2)  =  (2       1   0+2)  =  (2 1 2)
(7 2 3)        (0 0 0)      (7       2       3)       (7 2 3)

Now we see that Alice bought 6 peaches and Bob bought 2 zucchini. What we did is called matrix addition.

**Comment by mibrkelly** [comment]
I think that may already be too long and doesn't cover the material. Hopefully you can see how I am already setting up matrix multiplication with the way the people and fruit correspond to the numbers. Let me know if something like this is desirable, of if you just want straightforward definitions.

By the way, (a b c)T means (a b c) transpose, and is supposed to be a column.
