### ISSUE TITLE
Comprehensive list of tags and descriptions for videos

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide-articles#501]

**Comment by ewathedoer** [comment]
Some suggestions:
free code camp, learn to code, javascript, learn javascript, 

react, react js, flexbox, flexbox css, bootstrap, code vlog, d3, data visualisation, sass, 

git, learn github, github tutorial, maths for programmers, networks, design, UX

tech interview, become developer, free code camp summit

**Comment by QuincyLarson** [comment]
Thanks, @ewathedoer. These look like solid suggestions. @Septimus have you all started the process of updating the boilerplate and tags yet?

**Comment by Septimus** [comment]
@QuincyLarson Working on it. Reading a lot to make sure they are good. Haven't had a lot of time lately with the new job to get them in. Should be in by the weekends end.

**Comment by QuincyLarson** [comment]
@Septimus awesome - thanks for the update. I'm sure there are plenty of best practice primers.
