### ISSUE TITLE
HTML Lists

### ISSUE THREAD

**Issue by HKuz** [freeCodeCamp/guide-articles#511]
#### Potential URL:

/Web-Development/HTML/Elements/HTML-Lists
#### Suggested Reading:

[WebAIM article about list use](http://webaim.org/techniques/semanticstructure/#lists)
#### Draft of Article:

Cover ordered (`ol`) and unordered (`ul`) lists, list items (`li`), and definition lists (`dl`, `dt`, and `dd` elements)

**Comment by Prerna-kaushal24** [comment]
how to become a webdeveloper?? what are d skills needed for it?
