### ISSUE TITLE
A Few Useful Things to Know about Machine Learning

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/guide-articles#517]
#### Potential URL:

~~/Data-Science/Machine-Learning/Useful-Things-To-Know~~
/Machine-Learning/Principles/section-name-here

#### Suggested Reading:

https://homes.cs.washington.edu/~pedrod/papers/cacm12.pdf

#### Draft of Article:

- [ ] Learning = Representation + Evaluation + Optimization
- [ ] It's Generalization that Counts
- [ ] Data Alone is Not Enough
- [ ] Overfitting Has Many Faces
- [ ] Intuition Fails in High Dimensions
- [ ] Theoretical Guarantees are Not What They Seem
- [ ] Feature Engineering is the Key
- [ ] More Data Beats a Cleverer Algorithm
- [ ] Learn Many Models, Not Just One
- [ ] Simplicity Does Not Imply Accuracy
- [ ] Representable Does Not Imply Learnable
- [ ] Correlation Does Not Imply Causation

**Comment by QuincyLarson** [comment]
@erictleung This is an awesome list of principles and I am getting excited about reading these once they're ready.

We would want to break all of these out into more modular articles within a series of articles. The URLs could be something /Machine-Learning/Principles/Data-Alone-is-not-Enough

Also, I think Machine Learning is a broad enough topic that we'd want it to be at the top level of our  guides - not nested within Data Science.
