### ISSUE TITLE
CSS Selectors

### ISSUE THREAD

**Issue by HKuz** [freeCodeCamp/guide-articles#542]
#### Potential URL:

/Web-Development/CSS/Selectors
#### Suggested Reading:

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors
#### Draft of Article:

- what a CSS selector is (within a CSS style rule)
- CSS selectors: universal (\*), type (p, h1, etc.), class (.className), ID (#searchBar), child (ul>li), descendant (ul li), adjacent sibling (h2+p), and general sibling (h2~p)
- Pseudo selectors (:hover, :focus, :active, :link, :visited, etc.)
- Attribute selectors (how to create rules that apply to elements that have an attribute with a specific value): div[class], div[class="title"], div[class~="title"], div[attr\*"title"], div[^="ti"], div[$="tle"]

**Comment by QuincyLarson** [comment]
@HKuz I'm turning this issue into a bunch of stubs. Here's the directory hierarchy (@bouncey said he can add the index.md stub files programmatically later).
