### ISSUE TITLE
Add link to Article-Style-Guide.md to article placeholder copy

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide-articles#558]
We should add the following to the article placeholder copy:

[This quick style guide will help ensure your pull request gets accepted](https://github.com/freeCodeCamp/guide-articles/blob/master/article-style-guide.md).

**Comment by HKuz** [comment]
@Bouncey - just a head's up, after discussing with @QuincyLarson, I'm going to merge the style guide into the README (this evening or tomorrow) so there's only one document contributors have to reference. If you beat me to it, just link to the README.md file in the article placeholder.

**Comment by Bouncey** [comment]
Not a problem, I'll adjust the article stub when you have the README updated :+1:
