### ISSUE TITLE
What is an algorithm?

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide-articles#57]

**Comment by venegu** [comment]
If this hasn't been done yet, I would be glad to take care of making a video for this. I'm just curious of what the format of the video needs to be. Let me know when you can :panda_face:!

**Comment by PizzaPokerGuy** [comment]
Hey Venegu, 

If you haven't done this yet mind if I do it?

**Comment by brianamarie** [comment]
@PizzaPokerGuy @venegu I don't think anyone has written a script for this, but whoever would like to, go for it! 

If/when someone claims it and starts a script, I'll mark this as 'scripting'! 👍 🎉

**Comment by PizzaPokerGuy** [comment]
Do I need to write a script and submit it for approval?

**Comment by atjonathan** [comment]
@PizzaPokerGuy, correct, you should submit a pull request with the script. We will then review it :smile:

**Comment by PizzaPokerGuy** [comment]
Yes, I'll submit a short script by tomorrow.

**Comment by PizzaPokerGuy** [comment]
Script has been uploaded.

**Comment by atjonathan** [comment]
@PizzaPokerGuy, please submit a pull request with the script from your fork :smile:

**Comment by PizzaPokerGuy** [comment]
@atjonathan Sorry, still a bit rough with GitHub. I believe I have done the pull request correctly though.

**Comment by atjonathan** [comment]
@PizzaPokerGuy, please submit the script as a markdown file (`.md`).

**Comment by PizzaPokerGuy** [comment]
@atjonathan Should be in markdown format now.

**Comment by PizzaPokerGuy** [comment]
@QuincyLarson @atjonathan @venegu Here is my example video: let me know if it works for you.
https://youtu.be/kt7GOXd_n24

**Comment by PizzaPokerGuy** [comment]
Also, I have better audio for it, but I didn't sync it up yet. If it gets approved I'll edit the audio.

**Comment by atjonathan** [comment]
@PizzaPokerGuy, I can't see your pull request with the script :disappointed:

**Comment by PizzaPokerGuy** [comment]
I did another pull. Let me know if you still can't see the script.

**Comment by atjonathan** [comment]
@PizzaPokerGuy, it's working now :tada:
