### ISSUE TITLE
What are threads?

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide-articles#59]

**Comment by highlanderkev** [comment]
Threads can best be understood as a slice of a single process. The slice does not require as many resources as the overall process and tends to only run for a fraction of the overall process execution time. Threads share memory space and resources between themselves where as processes do not. Many threads can be running at once or in parallel which improves performance of programs and/or the operating system.

A process tends to be defined as a program in execution, typically using a processor to run the execution. The processor (CPU) is in charge of allocating memory or resources, coordinating input/output (IO) and doing any calculation needed by the process. 

With the rise of Multi-core processors, came the ability of the operating system to perform multi-tasking and this has been further improved via the rise of threads and the ability to do multi-threading. Multi-tasking is generally referred to the operating system's ability to run multiple programs at a single time (or in parallel). Initially multitasking was done on a single core processor via the use of context-switching and scheduling but became much faster and more performant with the use of multi-core processors and later multi-threading processors/operating systems. 

A web browser typically runs on a single threaded model where as Javascript is executed in sequential order (events, timeouts and ajax requests allow for asynchronous functionality in JavaScript) and multi-threading is typically not allowed. More recently, web browsers such as Chrome and Firefox have started to implement Service Workers (experimental currently) which allow for pseudo-type multi-threading, where a background script/process runs in parallel to the webpage.
