### ISSUE TITLE
How does a motherboard work?

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide-articles#76]

**Comment by brianamarie** [comment]
@QuincyLarson Do you think we need to do a video on this going into more detail, or do you think it's covered enough in the existing [More Computer Hardware](https://www.youtube.com/watch?v=xj9mFD71Vfc&list=PLWKjhJtqVAbmfoj2Th9fvxhHIeqFO7wOy&index=2) video?
