### ISSUE TITLE
What is a Derivative?

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide-articles#82]

**Comment by SEGrooms** [comment]
∆y/∆x = f(x0+∆x) - f(x0)/∆x =  average rate of change of a particle. A derivative of the function
f(x) = f'(x) = dy/dx = lim ∆x -->0 ∆y/∆x = lim ∆x-->0 f(x0+∆x) - f(x0)/∆x = instantaneous rate of change of a particle. (i.e. the change a an INSTANT in time)

Common notation is to let h = ∆x. Geometric interpretation helps with the explanation, which is impossible to type.

**Comment by liberaltech** [comment]
The rate at which the value of a function F(x) changes with respect to the change of the variable x.
