### ISSUE TITLE
What is a Mean?

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide-articles#90]

**Comment by matthras** [comment]
Slides have been written, can be viewed here: http://matthras.github.io/fcc-videos/whatisamean.html

**Comment by brianamarie** [comment]
@matthras I love your slides! It's difficult for me to imagine how you'll use these in a video, but after watching your video on statistics, I'm not worried about it! 😄 Be confident in how you want to present material, and if you want to split this up into several videos, go for it. If not, that's totally cool, too!

I want to bring attention to how awesome it is that your slides exist in a **version controlled github pages format**! 💯 @atjonathan @QuincyLarson In the future, this could be a very interesting way of storing scripts! What do you think?

**Comment by atjonathan** [comment]
@brianamarie, defiantly! I'm not sure how we would store whole scripts (word for word). But for general notes and pointers sorta like flash cards it would be awesome!!

**Comment by QuincyLarson** [comment]
@brianamarie @atjonathan @matthras I think the main places these videos will be on YouTube and to a lesser extent on Free Code Camp itself (I think we will get a lot more organic search traffic within YouTube from non-registered campers).

We shouldn't give them "a small exercise" at the end of these videos. Here's why:

1) The purpose of these videos is to expand learners' familiarity with concepts in as quick and easy a way as possible. We do some true/false comprehension checks after the video if they're watching it on freecodecamp.com. That is the absolute minimum required effort, and as I said, a majority of people will be watching these on YouTube where there are no comprehension checks.

2) It is unrealistic to expect viewers to open up a REPL and try out the specific concept you've just taught them (they are most likely on their phones commuting - they probably don't even have ready access to a desktop environment).

3) By asking them to do things they aren't realistically going to do, they will start to feel like they are cheating by not doing these. This is a negative association. It will cause them to stop watching. We want learners to binge-watch these lessons and get rapid (though superficial) exposure to as many of these concepts as possible.

I still strongly prefer the whiteboard to slides. They seem less polished and more "real".

**Comment by martinr74** [comment]
?

**Comment by matthras** [comment]
Can't disagree with you there, @QuincyLarson . The 'leaving a question at the end' thing is something that came from my teaching mathematics, where it's typical to lead students on with questions to encourage them to think. That said, you're right in that the format of these videos don't agree with that.

No issues with switching to a whiteboard - teaching at three universities does give me ample access to empty whiteboard filled classrooms!

**Comment by QuincyLarson** [comment]
@matthras awesome! Yes - my theory is that "a teacher in front of a whiteboard in a classroom" will achieve several things:
1. more immediate credibility (since this is the incumbent teaching modality).
2. these videos will remain timeless, where as the green screen videos will start to look dated as visual design sensibilities - and slide decks aesthetics - change over time.
3. viewers will apply a less critical eye - and be more metered in their criticism - than they would a polished presentation.
4. the viewers' focus will be on the person talking and the content, rather than the potentially distracting graphics.

There are probably a bunch of other reasons that most MOOCs still use whiteboards instead of green screens, but the benefits I argued above should outweigh most of the benefits of a green screen approach.

Also, I am thrilled that you have university teaching experience and access to classroom environments! I am excited to watch your future videos :)

**Comment by matthras** [comment]
@atjonathan @SEGrooms Draft video up: https://youtu.be/xMaqC_IRyAA

Just note that I've winged most of it: both the talking and what to put on the whiteboard. When I re-record this I'll prepare a script and what to put on the whiteboard.
