### ISSUE TITLE
What is a median?

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide-articles#92]

**Comment by matthras** [comment]
@atjonathan @SEGrooms Draft video up: https://youtu.be/Dr4ZPl1cS-M

Just note that I've winged most of it: both the talking and what to put on the whiteboard. When I re-record this I'll prepare a script and what to put on the whiteboard.

**Comment by QuincyLarson** [comment]
@matthras awesome! This is a solid draft. Your presentation and explanation are excellent. Also, the classroom environment and lighting 

I'm no AV expert, but I think there should be a way to get less echo-y audio on this. 

@SEGrooms @brianamarie @mpaluru do any of you know whether a lavaliere microphone will help in an echo-y room?

Also, I noticed toward a few times where your hands got closer to the camera, and it attempted to refocus. This caused a distracting out-of-focus effect. What camera did you using to record this? There might be a way to disable this feature.

**Comment by matthras** [comment]
@QuincyLarson I agree with the audio being a little too echo-y, and am planning to try next week with my Blue Yeti (condenser microphone) which should give better results.

The camera was a Logitech c930e webcam and I've had that refocusing issue before. That's definitely on the to-do list to check through when I record next week. 

Thanks for the quick feedback - I plan to rerecord on Tuesday 20th Dec.

**Comment by QuincyLarson** [comment]
@matthras Great - good luck with these AV fixes. I am excited to watch your upcoming videos 😄

**Comment by mpaluru** [comment]
@QuincyLarson I believe the microphone being close to the speaker definitely reduces the echo-y effect.

**Comment by QuincyLarson** [comment]
Thanks, @mpaluru. 

You might want to order a lavaliere microphone. 

Here is a good, inexpensive one: https://www.amazon.com/Lavalier-microphone-hands-free-condenser-smartphones/dp/B01FT3XJNC/ref=lp_11974761_1_16?s=musical-instruments&ie=UTF8&qid=1481742077&sr=1-16

I don't know of one that is compatible with that camera. @mpaluru has a great tripod setup where he uses his iPhone 5 with a lavaliere and the sounds was excellent.
